---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-one
  labels:
    app: app-one
    name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
      task: app-one
  template:
    metadata:
      labels:
        app: app-one
        task: app-one
    spec:
      hostNetwork: true
      containers:
        - name: app-one
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
          
---
